services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TTL=${REDIS_TTL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
